create table if not exists public.event_analyses (
    id bigint generated by default as identity primary key,
    event_id bigint not null unique references public.events(id) on delete cascade,
    status text not null default 'pending',
    research jsonb not null default '{}'::jsonb,
    analysis jsonb not null default '{}'::jsonb,
    numeric_evidence jsonb not null default '{}'::jsonb,
    data_story jsonb not null default '{}'::jsonb,
    data_questions jsonb not null default '[]'::jsonb,
    evidence_count integer not null default 0,
    metric_count integer not null default 0,
    data_point_count integer not null default 0,
    generated_at timestamptz,
    updated_at timestamptz not null default now()
);

alter table public.event_analyses
    add column if not exists numeric_evidence jsonb not null default '{}'::jsonb,
    add column if not exists data_story jsonb not null default '{}'::jsonb,
    add column if not exists data_questions jsonb not null default '[]'::jsonb,
    add column if not exists evidence_count integer not null default 0,
    add column if not exists metric_count integer not null default 0,
    add column if not exists data_point_count integer not null default 0;

alter table public.events
    add column if not exists background_sources jsonb not null default '[]'::jsonb,
    add column if not exists numeric_data jsonb not null default '[]'::jsonb;

create index if not exists event_analyses_status_idx
    on public.event_analyses(status);
